# ROSE-LINK Grafana Datasources Provisioning
apiVersion: 1

datasources:
  # Prometheus - Primary metrics source
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false
    jsonData:
      timeInterval: "10s"
      httpMethod: POST
      manageAlerts: true
      prometheusType: Prometheus
      prometheusVersion: 2.47.0

  # JSON API - For performance metrics endpoint
  - name: ROSE-LINK-API
    type: grafana-simple-json-datasource
    access: proxy
    url: http://host.docker.internal:8000
    isDefault: false
    editable: false
